# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TestMark' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
pod 'SDWebImage'
pod 'YYKit'
pod 'AFNetworking'
pod 'CLImageEditor'
pod 'MBProgressHUD'
pod 'SVProgressHUD'
  # Pods for TestMark

end
